server:
  port:
    8080
spring:
  datasource:
    url:
      jdbc:postgresql://localhost:5432/telegram-bot
    username:
      postgres
    password:
      root
  jpa:
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
    generate-ddl:
      true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:
              true
        temp:
          use_jdbc_metadata_defaults:
            false
bot:
  username:
    bsc-homework-checker
  token:
    2103962833:AAHbXuHbKfoh3vqnB-icYYI46Frlnj1THw4
