spring:
  data:
    mongodb:
      username: test
      password: test
      host: localhost
      port: 27017
      database: mongo

bot:
  username:
    bsc-homework-checker
  token:
    2103962833:AAHbXuHbKfoh3vqnB-icYYI46Frlnj1THw4
